* TODOS
** show the soft sketch
*** choice ui framework.
**** check the wechat dll ui.
***** use lua(yes, familiar) to check the ui framework.

2. open the image or choice the previous opened img, and can delete.

* Some boring thing
qt is free for personal use?

ultlmate++ is what?

wxWidgets is good and powerful?

* Error
====================[ Build | pic_tool | Debug ]================================
"E:\Program Files\JetBrains\CLion 2020.2.3\bin\cmake\win\bin\cmake.exe" --build F:\pic_tool\cmake-build-debug --target pic_tool
[ 12%] Linking CXX executable pic_tool.exe
NMAKE : fatal error U1077: “"E:\Program Files\JetBrains\CLion 2020.2.3\bin\cmake\win\bin\cmake.exe"”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"E:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"E:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"E:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
LINK Pass 1: command "E:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\pic_tool.dir\objects1.rsp /out:pic_tool.exe /implib:pic_tool.lib /pdb:F:\pic_tool\cmake-build-debug\pic_tool.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console E:\source\vcpkg\installed\x64-windows\debug\lib\Qt5Widgetsd.lib E:\source\vcpkg\installed\x64-windows\debug\lib\Qt5Guid.lib E:\source\vcpkg\installed\x64-windows\debug\lib\Qt5Cored.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\pic_tool.dir/intermediate.manifest CMakeFiles\pic_tool.dir/manifest.res" failed (exit code 1169) with the following output:
CMakeCXXCompilerId.cpp.obj : error LNK2005: main 已经在 CMakeCCompilerId.c.obj 中定义
CMakeCCompilerId.c.obj : error LNK2005: info_compiler 已经在 CMakeCCompilerId.c.obj 中定义
CMakeCCompilerId.c.obj : error LNK2005: info_version 已经在 CMakeCCompilerId.c.obj 中定义
CMakeCCompilerId.c.obj : error LNK2005: info_platform 已经在 CMakeCCompilerId.c.obj 中定义
CMakeCCompilerId.c.obj : error LNK2005: info_arch 已经在 CMakeCCompilerId.c.obj 中定义
CMakeCCompilerId.c.obj : error LNK2005: info_language_dialect_default 已经在 CMakeCCompilerId.c.obj 中定义
CMakeCCompilerId.c.obj : error LNK2005: main 已经在 CMakeCCompilerId.c.obj 中定义
CMakeCXXCompilerId.cpp.obj : error LNK2005: "char const * const info_compiler" (?info_compiler@@3PEBDEB) 已经在 CMakeCXXCompilerId.cpp.obj 中定义
CMakeCXXCompilerId.cpp.obj : error LNK2005: "char const * const info_platform" (?info_platform@@3PEBDEB) 已经在 CMakeCXXCompilerId.cpp.obj 中定义
CMakeCXXCompilerId.cpp.obj : error LNK2005: "char const * const info_arch" (?info_arch@@3PEBDEB) 已经在 CMakeCXXCompilerId.cpp.obj 中定义
CMakeCXXCompilerId.cpp.obj : error LNK2005: "char const * const info_language_dialect_default" (?info_language_dialect_default@@3PEBDEB) 已经在 CMakeCXXCompilerId.cpp.obj 中定义
CMakeCXXCompilerId.cpp.obj : error LNK2005: main 已经在 CMakeCCompilerId.c.obj 中定义
main.cc.obj : error LNK2005: main 已经在 CMakeCCompilerId.c.obj 中定义
pic_tool.exe : fatal error LNK1169: 找到一个或多个多重定义的符