//
// Created by huhua on 2022/1/22.
//

#ifndef PICTOOL_SRC_UI_PANEL_RECENTLY_RECENTLY_PANEL_H_
#define PICTOOL_SRC_UI_PANEL_RECENTLY_RECENTLY_PANEL_H_

class RecentlyPanel {

};

#endif //PICTOOL_SRC_UI_PANEL_RECENTLY_RECENTLY_PANEL_H_
